export const DIAGNOSES_CATEGORY = {
  schizophrenia: "P",
  schizoaffective: "P",
  bipolar: "P",
  psychosis: "P",
  psychotic: "P",
  ocd: "P",
  delusion: "P",
  hallucination: "P",
  dementia: "N",
  neurocognitive: "N",
  cognitive: "N",
  cognition: "N",
  huntington: "O",
  bpsd: "N",
  behavioral_disturbance: "N",
  ncd: "N",
};

export const ANTIPSYCHOTICS_CATEGORY = {
  amisulpride: "Y",
  aripiprazole: "Z",
  asenapine: "Y",
  brexpiprazole: "Z",
  cariprazine: "Y",
  chlorpromazine: "Y",
  clozapine: "Y",
  droperidol: "Y",
  flupentixol: "Y",
  fluphenazine: "Y",
  haloperidol: "Z",
  iloperidone: "Y",
  loxapine: "Z",
  lumateperone: "Y",
  lurasidone: "Y",
  molindone: "Y",
  olanzapine: "Z",
  paliperidone: "Y",
  perphenazine: "Y",
  pimavanserin: "Y",
  pimozide: "Y",
  prochlorperazine: "Y",
  quetiapine: "Z",
  risperidone: "Z",
  sertindole: "Y",
  thioridazine: "Y",
  thiothixene: "Y",
  trifluoperazine: "Y",
  ziprasidone: "Y",
  zotepine: "Y",
  zuclopenthixol: "Y",
  methotrimeprazine: "Z",
  depot: "Y",
  long_acting: "Y",
  lai: "Y",
};

export const BEHAVIOR_RESPONSIVENESS = {
  delirium: 1,
  delusions: 2,
  paranoia: 2,
  auditory_hallucinations: 2,
  visual_hallucinations: 2,
  depression: 0,
  low_mood: 0,
  anxiety: 0,
  irritability: 0,
  crying: 0,
  apathy: 0,
  resistance_to_care: 1,
  sexually_inappropriate_behavior: 1,
  physical_aggression: 1,
  verbal_aggression: 1,
  calling_out: 0,
  repetitive_activities: 0,
  hoarding: 0,
  incontinence: 0,
  inappropriate_undressing: 0,
  inappropriate_defecation: 0,
  inappropriate_urination: 0,
  wandering: 0,
  exit_seeking: 0,
  sundowning: 1,
  insomnia: 0,
  climbing_out: 0,
  spitting: 0,
};

export const DURATION_NUMBER = {
  "stable>3months": 1,
  "stable<3months": 2,
  ongoing: 3,
};

export const CODE_RECOMMENDATIONS = {
  0: {
    msg: "Likely inappropriate. No behaviors identifed. Trial taper of AP",
    danger: 1,
  },
  11: {
    msg: "Likely inappropriate. Trial non-pharmacological approaches. Trial taper of AP.",
    danger: 1,
  },
  12: {
    msg: "Likely inappropriate. Trial non-pharmacological approaches. Trial taper of AP.",
    danger: 1,
  },
  13: {
    msg: "Likely inappropriate. Trial non-pharmacological approaches. Trial taper of AP.",
    danger: 1,
  },
  21: {
    msg: "Possibly inappropriate. Trial non-pharmacological approaches. Trial taper of AP. Consider alternative medications.",
    danger: 2,
  },
  22: {
    msg: "Possibly inappropriate. Trial non-pharmacological approaches. Trial taper of AP. Consider alternative medications.",
    danger: 2,
  },
  23: {
    msg: "Possibly inappropriate. Trial non-pharmacological approaches. Trial taper of AP. Consider alternative medications.",
    danger: 2,
  },
  31: {
    msg: "Possibly appropriate. Trial non-pharmacological approaches. Trial taper of AP. Consider Geriatric Psychiatry referral.",
    danger: 3,
  },
  32: {
    msg: "Possibly appropriate. Trial non-pharmacological approaches. Continue AP. Consider Geriatric Psychiatry referral to review potential tapering.",
    danger: 3,
  },
  33: {
    msg: "Possibly appropriate. Trial non-pharmacological approaches. Continue AP. Consider Geriatric Psychiatry referral to review potential tapering.",
    danger: 3,
  },
  99: {
    msg: "Likely inappropriate. No behaviors identifed. Trial taper of AP.",
    danger: 1,
  },
  O: {
    msg: "Likely appropriate. Continue AP.",
    danger: 4,
  },
  P: {
    msg: "Likely appropriate. Continue AP.",
    danger: 4,
  },
  PN: {
    msg: "Likely appropriate. Continue AP. Consider Geriatric Psychiatry referral to review potential tapering.",
    danger: 4,
  },
  ON: {
    msg: "Likely appropriate. Continue AP. Consider Geriatric Psychiatry referral to review potential tapering.",
    danger: 4,
  },
  W: {
    msg: "No AP prescribed.",
    danger: 4,
  },
};
