export const DIAGNOSES_CATEGORY = {
  schizophrenia: "P",
  schizoaffective: "P",
  bipolar: "P",
  psychosis: "P",
  psychotic: "P",
  ocd: "P",
  delusion: "P",
  hallucination: "P",
  dementia: "N",
  neurocognitive: "N",
  cognitive: "N",
  cognition: "N",
  huntington: "O",
  bpsd: "N",
  behavioral_disturbance: "N",
  ncd: "N",
};

export const ANTIPSYCHOTICS_CATEGORY = {
  amisulpride: "Y",
  aripiprazole: "Z",
  asenapine: "Y",
  brexpiprazole: "Z",
  cariprazine: "Y",
  chlorpromazine: "Y",
  clozapine: "Y",
  droperidol: "Y",
  flupentixol: "Y",
  fluphenazine: "Y",
  haloperidol: "Z",
  iloperidone: "Y",
  loxapine: "Z",
  lumateperone: "Y",
  lurasidone: "Y",
  molindone: "Y",
  olanzapine: "Z",
  paliperidone: "Y",
  perphenazine: "Y",
  pimavanserin: "Y",
  pimozide: "Y",
  prochlorperazine: "Y",
  quetiapine: "Z",
  risperidone: "Z",
  sertindole: "Y",
  thioridazine: "Y",
  thiothixene: "Y",
  trifluoperazine: "Y",
  ziprasidone: "Y",
  zotepine: "Y",
  zuclopenthixol: "Y",
  methotrimeprazine: "Z",
  depot: "Y",
  long_acting: "Y",
  lai: "Y",
};

export const BEHAVIOR_RESPONSIVENESS = {
  delirium: 1,
  delusions: 2,
  paranoia: 2,
  auditory_hallucinations: 2,
  visual_hallucinations: 2,
  depression: 0,
  low_mood: 0,
  anxiety: 0,
  irritability: 0,
  crying: 0,
  apathy: 0,
  resistance_to_care: 1,
  sexually_inappropriate_behavior: 1,
  physical_aggression: 1,
  verbal_aggression: 1,
  calling_out: 0,
  repetitive_activities: 0,
  hoarding: 0,
  incontinence: 0,
  inappropriate_undressing: 0,
  inappropriate_defecation: 0,
  inappropriate_urination: 0,
  wandering: 0,
  exit_seeking: 0,
  sundowning: 1,
  insomnia: 0,
  climbing_out: 0,
  spitting: 0,
};

export const DURATION_NUMBER = {
  "1-stable>3months": 1,
  "2-stable<3months": 2,
  "3-ongoing": 3,
};

export const CODE_RECOMMENDATIONS = {
  0: "Likely inappropriate. No behaviors identifed. Trial taper of AP",
  11: "Likely inappropriate. Trial non-pharmacological approaches. Trial taper of AP.",
  12: "Likely inappropriate. Trial non-pharmacological approaches. Trial taper of AP.",
  13: "Likely inappropriate. Trial non-pharmacological approaches. Trial taper of AP.",
  21: "Possibly inappropriate. Trial non-pharmacological approaches. Trial taper of AP. Consider alternative medications.",
  22: "Possibly inappropriate. Trial non-pharmacological approaches. Trial taper of AP. Consider alternative medications.",
  23: "Possibly inappropriate. Trial non-pharmacological approaches. Trial taper of AP. Consider alternative medications.",
  31: "Possibly appropriate. Trial non-pharmacological approaches. Trial taper of AP. Consider Geriatric Psychiatry referral.",
  32: "Possibly appropriate. Trial non-pharmacological approaches. Continue AP. Consider Geriatric Psychiatry referral to review potential tapering.",
  33: "Possibly appropriate. Trial non-pharmacological approaches. Continue AP. Consider Geriatric Psychiatry referral to review potential tapering.",
  99: "Likely inappropriate. No behaviors identifed. Trial taper of AP.",
  O: "Likely appropriate. Continue AP.",
  P: "Likely appropriate. Continue AP.",
  PN: "Likely appropriate. Continue AP. Consider Geriatric Psychiatry referral to review potential tapering.",
  ON: "Likely appropriate. Continue AP. Consider Geriatric Psychiatry referral to review potential tapering.",
  W: "No AP prescribed.",
};
